---
  defaultImage: false
  image: "harbor.io/library/confluentinc/cp-kafka"
  imageTag: "4.0.1-1"
  zookeeper: 
    image: 
      repository: "harbor.io/library/confluentinc/cp-zookeeper"
      tag: "4.1.1"
    persistence: 
      enabled: false
      size: "10Gi"
      storageClass: ""
  schema-registry: 
    image: "harbor.io/library/confluentinc/cp-schema-registry"
    imageTag: "4.0.1"
  kafka-rest: 
    image: 
      repository: "harbor.io/library/confluentinc/cp-kafka-rest"
      tag: "4.0.0"
  kafka-topics-ui: 
    image: 
      repository: "harbor.io/library/landoop/kafka-topics-ui"
      tag: "latest"
    enabled: true
    ingress: 
      enabled: false
      hosts: 
        - "xip.io"
    service: 
      type: "NodePort"
      nodePort: "30061"
  replicas: "3"
  persistence: 
    enabled: true
    size: "50Gi"
    storageClass: "openebs-jiva-default"
